development:
    sessions:
      default:
        database: site_arthur_carvalho_development
        hosts:
          - localhost:27017


production:
  sessions:
    default:
      uri: <%= ENV['MONGODB_URI'] %>


test:
  clients:
    default:
      database: site_arthur_carvalho_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
