development:
  # Configure available database clients. (required)
  clients:
    # Defines the default client. (required)
    default:
      database: site_arthur_carvalho_development
      hosts:
        - localhost:27017
      options:
        
staging:
  sessions:
    default:
      uri: <%= ENV['MONGODB_URI'] %>

production:
  sessions:
    default:
      uri: <%= ENV['MONGOHQ_URL'] %>
test:
  clients:
    default:
      database: site_arthur_carvalho_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
